// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEhvm944wV627IH0inZz85v4ucX-pKGYU',
    appId: '1:322415995757:android:76bf99848061fd3ce48864',
    messagingSenderId: '322415995757',
    projectId: 'easy-pg-2a0d6',
    storageBucket: 'easy-pg-2a0d6.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISVuP_BovZYKqro5vCxHh3RGIjM9U7uE',
    appId: '1:322415995757:web:06115aceafb269a1e48864',
    messagingSenderId: '322415995757',
    projectId: 'easy-pg-2a0d6',
    authDomain: 'easy-pg-2a0d6.firebaseapp.com',
    storageBucket: 'easy-pg-2a0d6.appspot.com',
    measurementId: 'G-8VW5S4HRMH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5OVHEOV5fXr_P9--33LsCykfRE0I1o6g',
    appId: '1:322415995757:ios:1b8a30d563d65ea5e48864',
    messagingSenderId: '322415995757',
    projectId: 'easy-pg-2a0d6',
    storageBucket: 'easy-pg-2a0d6.appspot.com',
    iosBundleId: 'com.example.easypg',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5OVHEOV5fXr_P9--33LsCykfRE0I1o6g',
    appId: '1:322415995757:ios:4abb6f4979fa547be48864',
    messagingSenderId: '322415995757',
    projectId: 'easy-pg-2a0d6',
    storageBucket: 'easy-pg-2a0d6.appspot.com',
    iosBundleId: 'com.fuinc.easypg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISVuP_BovZYKqro5vCxHh3RGIjM9U7uE',
    appId: '1:322415995757:web:ac00794005d82303e48864',
    messagingSenderId: '322415995757',
    projectId: 'easy-pg-2a0d6',
    authDomain: 'easy-pg-2a0d6.firebaseapp.com',
    storageBucket: 'easy-pg-2a0d6.appspot.com',
    measurementId: 'G-JHPJ1BL6R8',
  );

}